### ISSUE TITLE
0.3.5 crash on start arcade mode

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#101]
[Reported by /u/japtar](https://www.reddit.com/r/gamedev/comments/4lzqy9/wip_wednesday_6_unlimited_budgets/d3tt7o5)

> I downloaded the jar file, and managed to run the menu, but the game crashed after clicking the Arcade mode. Am I doing something wrong?

System info: Windows 10 with JRE 8.0.91

App.log: 

```
[INFO]  18:52:30.736    tools.FileStructure.<init>  -   JAR detected
[INFO]  18:52:42.804    mixpanel.UserIdentifier.getId   -   UID:dd7bb8cf-2c51-43a2-be69-08b3e0fdca1a
[INFO]  18:52:42.809    mixpanel.UserIdentifier.getId   -   UID:dd7bb8cf-2c51-43a2-be69-08b3e0fdca1a
[INFO]  18:52:43.403    systems.MusicSystem.<init>  -   music loops loading from resources/sounds/music/arcade_30s_loops
[INFO]  18:52:43.845    cellrpg.PixelonTransmission.create  -   Game started
[INFO]  18:52:55.422    systems.MusicSystem.processSystem   -   12 music loops loaded
[INFO]  18:54:08.571    tools.Scores.saveScores -   saved scores to file
[INFO]  18:54:08.579    cellrpg.PixelonTransmission.dispose -   Game shutdown
[INFO]  19:51:22.351    mixpanel.UserIdentifier.getId   -   UID:dd7bb8cf-2c51-43a2-be69-08b3e0fdca1a
[INFO]  19:51:22.361    mixpanel.UserIdentifier.getId   -   UID:dd7bb8cf-2c51-43a2-be69-08b3e0fdca1a
[INFO]  19:51:22.856    systems.MusicSystem.<init>  -   music loops loading from resources/sounds/music/arcade_30s_loops
[INFO]  19:51:23.152    cellrpg.PixelonTransmission.create  -   Game started
[INFO]  19:51:34.379    systems.MusicSystem.processSystem   -   12 music loops loaded
[INFO]  19:56:13.822    systems.MusicSystem.<init>  -   music loops loading from resources/sounds/music/arcade_30s_loops
[INFO]  19:56:13.835    game.Arcade.<init>  -   enter arcade mode
[INFO]  19:56:36.894    mixpanel.UserIdentifier.getId   -   UID:dd7bb8cf-2c51-43a2-be69-08b3e0fdca1a
[INFO]  19:56:36.905    mixpanel.UserIdentifier.getId   -   UID:dd7bb8cf-2c51-43a2-be69-08b3e0fdca1a
[INFO]  19:56:37.390    systems.MusicSystem.<init>  -   music loops loading from resources/sounds/music/arcade_30s_loops
[INFO]  19:56:37.761    cellrpg.PixelonTransmission.create  -   Game started
[INFO]  19:56:48.374    systems.MusicSystem.processSystem   -   12 music loops loaded
[ERROR] 19:56:48.424    pause.EquipmentMenu.launchSubmenu   -   cannot show equipment (player not instantiated?)
java.lang.NullPointerException
    at io.github.emergentorganization.cellrpg.scenes.game.menu.pause.EquipmentMenu.launchSubmenu(EquipmentMenu.java:52) [desktop.jar:?]
    at io.github.emergentorganization.cellrpg.scenes.game.menu.pause.Submenu$1.clicked(Submenu.java:29) [desktop.jar:?]
    at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89) [desktop.jar:?]
    at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58) [desktop.jar:?]
    at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348) [desktop.jar:?]
    at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:306) [desktop.jar:?]
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207) [desktop.jar:?]
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120) [desktop.jar:?]
[INFO]  19:56:50.425    pause.PauseWindow.fadeOut   -   closing pause window
[INFO]  19:56:52.040    systems.MusicSystem.<init>  -   music loops loading from resources/sounds/music/arcade_30s_loops
[INFO]  19:56:52.056    game.Arcade.<init>  -   enter arcade mode
```

**Comment by 7yl4r** [comment]
NOTE: this app.log includes info from multiple runs of the program. Here's what it looks like to me:
1. game started for first time, game closed normally (never left menu)
2. Game started, arcade mode entered, game crash.
3. Game started, pause menu activated (and fiddled around, that NullPtrException is expected and handled properly), pause menu exited, clicked to enter arcade mode, game crash.

I don't really see anything useful in the log except for the fact that we get to Arcade.init before hitting a hard crash.

**Comment by BrianErikson** [comment]
I'm not sure how much more we'll be able to get out of this issue. Since then, there has been lots of changes. I'm going to close out this issue in favor of opening a new one once we get more data to back up this edge case.
